version: '3'
services:
  # build angular app and run api
  xevo-api:
    build: 
      context: .
      dockerfile: ./xevo-api/Dockerfile 
    ports:
      - "5566:5566"
    depends_on:
      - xevo-cpp-server
    networks:
      - xevo-network
    restart: always

  # run server
  xevo-cpp-server:
    build: ./xevo-cpp-server
    ports:
      - "8080:8080"
    networks:
      - xevo-network
    hostname: xevo-cpp-server
    restart: always

networks:
  xevo-network:
    driver: bridge
